# Generated by Django 2.2 on 2019-09-08 15:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(blank=True, max_length=250, null=True)),
                ('nirf_rank', models.IntegerField(default=0, null=True)),
                ('logo', models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('description', models.CharField(default='Ah! Description', max_length=1500, null=True)),
                ('is_IIT', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='cse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Computer Science and Engineering', max_length=200, null=True)),
                ('home_state', models.CharField(blank=True, choices=[('chhattisgarh', 'chhattisgarh'), ('rajasthan', 'rajasthan'), ('gujrat', 'gujrat'), ('karnataka', 'karnataka'), ('goa', 'goa')], max_length=100, null=True)),
                ('hs_open_cut', models.IntegerField(default=0, null=True)),
                ('hs_obc_cut', models.IntegerField(default=0, null=True)),
                ('hs_sc_cut', models.IntegerField(default=0, null=True)),
                ('hs_st_cut', models.IntegerField(default=0, null=True)),
                ('hs_ews_cut', models.IntegerField(default=0, null=True)),
                ('hs_open_f_cut', models.IntegerField(default=0, null=True)),
                ('hs_obc_f_cut', models.IntegerField(default=0, null=True)),
                ('hs_sc_f_cut', models.IntegerField(default=0, null=True)),
                ('hs_st_f_cut', models.IntegerField(default=0, null=True)),
                ('open_cut', models.IntegerField(default=0, null=True)),
                ('obc_cut', models.IntegerField(default=0, null=True)),
                ('sc_cut', models.IntegerField(default=0, null=True)),
                ('st_cut', models.IntegerField(default=0, null=True)),
                ('ews_cut', models.IntegerField(default=0, null=True)),
                ('open_f_cut', models.IntegerField(default=0, null=True)),
                ('obc_f_cut', models.IntegerField(default=0, null=True)),
                ('sc_f_cut', models.IntegerField(default=0, null=True)),
                ('st_f_cut', models.IntegerField(default=0, null=True)),
                ('ad_open_cut', models.IntegerField(default=0, null=True)),
                ('ad_obc_cut', models.IntegerField(default=0, null=True)),
                ('ad_sc_cut', models.IntegerField(default=0, null=True)),
                ('ad_st_cut', models.IntegerField(default=0, null=True)),
                ('ad_ews_cut', models.IntegerField(default=0, null=True)),
                ('ad_open_f_cut', models.IntegerField(default=0, null=True)),
                ('ad_obc_f_cut', models.IntegerField(default=0, null=True)),
                ('ad_sc_f_cut', models.IntegerField(default=0, null=True)),
                ('ad_st_f_cut', models.IntegerField(default=0, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_predictor.College')),
            ],
        ),
    ]
