# Generated by Django 2.2 on 2019-09-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cse',
            name='ad_ews_f_cut',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='cse',
            name='ews_f_cut',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='cse',
            name='hs_ews_f_cut',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
