# Generated by Django 2.2 on 2019-09-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_predictor', '0003_auto_20190909_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='name',
        ),
        migrations.AddField(
            model_name='cse',
            name='name',
            field=models.CharField(default='Computer Science and Engineering', max_length=200, null=True),
        ),
    ]
