# Generated by Django 2.2 on 2019-09-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_predictor', '0004_auto_20190909_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='home_state',
            field=models.CharField(blank=True, choices=[('IIT or IIIT', 'IIT or IIIT'), ('chhattisgarh', 'chhattisgarh'), ('rajasthan', 'rajasthan'), ('gujrat', 'gujrat'), ('karnataka', 'karnataka'), ('goa', 'goa'), ('punjab', 'punjab'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Tripura', 'Tripura'), ('Kerla', 'Kerla'), ('Delhi', 'Delhi'), ('West Bengal', 'West Bengal'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Meghalaya', 'Meghalaya'), ('Nagaland', 'Nagaland'), ('Bihar', 'Bihar'), ('Puducherry', 'Puducherry'), ('Sikkim', 'Sikkim'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Haryana', 'Haryana'), ('Manipur', 'Manipur'), ('Mizoram', 'Mizoram'), ('Odisha', 'Odisha'), ('Assam', 'Assam'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Tamil Nadu', 'Tamil Nadu'), ('Uttarakhand', 'Uttarakhand'), ('Telangana', 'Telangana'), ('Maharashtra', 'Maharashtra')], max_length=100, null=True),
        ),
    ]
