# Generated by Django 2.2 on 2019-09-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_predictor', '0006_auto_20190917_2232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='min',
            new_name='mining',
        ),
    ]
