# Generated by Django 2.2 on 2019-09-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_predictor', '0007_auto_20190917_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='description',
            field=models.TextField(default='Ah! Description', max_length=1000, null=True),
        ),
    ]
