from django.db import models
from django.core.validators import FileExtensionValidator
# Create your models here.
class College(models.Model):
    college_name = models.CharField(max_length=250,blank= True, null= True)
    hs_choices= (
        ('IIT or IIIT','IIT or IIIT'),
        ('chhattisgarh','chhattisgarh'),
        ('rajasthan','rajasthan'),
        ('gujrat','gujrat'),
        ('karnataka','karnataka'),
        ('goa','goa'),
        ('punjab', 'punjab'),
        ('Madhya Pradesh', 'Madhya Pradesh'),
        ('Uttar Pradesh','Uttar Pradesh'),
        ('Tripura','Tripura'),
        ('Kerla','Kerla'),
        ('Delhi','Delhi'),
        ('West Bengal','West Bengal'),
        ('Himachal Pradesh', 'Himachal Pradesh'),
        ('Meghalaya', 'Meghalaya'),
        ('Nagaland','Nagaland'),
        ('Bihar','Bihar'),
        ('Puducherry', 'Puducherry'),
        ('Sikkim', 'Sikkim'),
        ('Arunachal Pradesh', 'Arunachal Pradesh'),
        ('Jharkhand','Jharkhand'),
        ('Haryana','Haryana'),
        ('Manipur', 'Manipur'),
        ('Mizoram', 'Mizoram'),
        ('Odisha', 'Odisha'),
        ('Assam','Assam'),
        ('Jammu and Kashmir','Jammu and Kashmir'),
        ('Tamil Nadu', 'Tamil Nadu'),
        ('Uttarakhand', 'Uttarakhand'),
        ('Telangana', 'Telangana'),
        ('Maharashtra','Maharashtra'),
        ('Andhra Pradesh', 'Andhra Pradesh'),
     )
    home_state= models.CharField(max_length=100, choices= hs_choices, blank= True, null= True)#probable error
    nirf_rank= models.IntegerField(default= 0,null= True)
    logo = models.FileField(null= True, validators=[FileExtensionValidator(allowed_extensions=['jpg','png'])])
    #description = models.CharField(max_length= 1500, default="Ah! Description", null= True)
    description = models.TextField(max_length= 1000,default="Ah! Description", null= True)
    is_IIT = models.BooleanField(default= False)
    #For detail page, I need to create more fields regarding details like distance from airport, file field of all branch cut off,facilities available etc
    def __str__(self):
        return self.college_name
class cse(models.Model):#1
    college= models.ForeignKey(College, on_delete= models.CASCADE)
    name = models.CharField(max_length= 200, default="Computer Science and Engineering", null= True)
    hs_open_cut = models.IntegerField(default=0, null= True)
    hs_obc_cut = models.IntegerField(default=0, null= True)
    hs_sc_cut = models.IntegerField(default=0, null= True)
    hs_st_cut = models.IntegerField(default=0, null= True)
    hs_ews_cut = models.IntegerField(default=0, null= True)
    hs_open_f_cut = models.IntegerField(default=0, null= True)
    hs_obc_f_cut = models.IntegerField(default=0, null= True)
    hs_sc_f_cut = models.IntegerField(default=0, null= True)
    hs_st_f_cut = models.IntegerField(default=0, null= True)
    hs_ews_f_cut = models.IntegerField(default=0, null= True)
    open_cut = models.IntegerField(default=0, null= True)
    obc_cut = models.IntegerField(default=0, null= True)
    sc_cut = models.IntegerField(default=0, null= True)
    st_cut = models.IntegerField(default=0, null= True)
    ews_cut = models.IntegerField(default=0, null= True)
    open_f_cut = models.IntegerField(default=0, null= True)
    obc_f_cut = models.IntegerField(default=0, null= True)
    sc_f_cut = models.IntegerField(default=0, null= True)
    st_f_cut = models.IntegerField(default=0, null= True) 
    ews_f_cut = models.IntegerField(default=0, null= True)
    ad_open_cut = models.IntegerField(default=0, null= True)
    ad_obc_cut = models.IntegerField(default=0, null= True)
    ad_sc_cut = models.IntegerField(default=0, null= True)
    ad_st_cut = models.IntegerField(default=0, null= True)
    ad_ews_cut = models.IntegerField(default=0, null= True)
    ad_open_f_cut = models.IntegerField(default=0, null= True)
    ad_obc_f_cut = models.IntegerField(default=0, null= True)
    ad_sc_f_cut = models.IntegerField(default=0, null= True)
    ad_st_f_cut = models.IntegerField(default=0, null= True) 
    ad_ews_f_cut = models.IntegerField(default=0, null= True)

    def __str__(self):
        return self.name + '-' + self.college.college_name
class IT(models.Model):#2
    college= models.ForeignKey(College, on_delete= models.CASCADE)
    name = models.CharField(max_length= 200, default="Information Technology", null= True)
    hs_open_cut = models.IntegerField(default=0, null= True)
    hs_obc_cut = models.IntegerField(default=0, null= True)
    hs_sc_cut = models.IntegerField(default=0, null= True)
    hs_st_cut = models.IntegerField(default=0, null= True)
    hs_ews_cut = models.IntegerField(default=0, null= True)
    hs_open_f_cut = models.IntegerField(default=0, null= True)
    hs_obc_f_cut = models.IntegerField(default=0, null= True)
    hs_sc_f_cut = models.IntegerField(default=0, null= True)
    hs_st_f_cut = models.IntegerField(default=0, null= True)
    hs_ews_f_cut = models.IntegerField(default=0, null= True)
    open_cut = models.IntegerField(default=0, null= True)
    obc_cut = models.IntegerField(default=0, null= True)
    sc_cut = models.IntegerField(default=0, null= True)
    st_cut = models.IntegerField(default=0, null= True)
    ews_cut = models.IntegerField(default=0, null= True)
    open_f_cut = models.IntegerField(default=0, null= True)
    obc_f_cut = models.IntegerField(default=0, null= True)
    sc_f_cut = models.IntegerField(default=0, null= True)
    st_f_cut = models.IntegerField(default=0, null= True) 
    ews_f_cut = models.IntegerField(default=0, null= True)
    ad_open_cut = models.IntegerField(default=0, null= True)
    ad_obc_cut = models.IntegerField(default=0, null= True)
    ad_sc_cut = models.IntegerField(default=0, null= True)
    ad_st_cut = models.IntegerField(default=0, null= True)
    ad_ews_cut = models.IntegerField(default=0, null= True)
    ad_open_f_cut = models.IntegerField(default=0, null= True)
    ad_obc_f_cut = models.IntegerField(default=0, null= True)
    ad_sc_f_cut = models.IntegerField(default=0, null= True)
    ad_st_f_cut = models.IntegerField(default=0, null= True) 
    ad_ews_f_cut = models.IntegerField(default=0, null= True)

    def __str__(self):
        return self.name + '-' + self.college.college_name
class EE(models.Model):#3
    college= models.ForeignKey(College, on_delete= models.CASCADE)
    name = models.CharField(max_length= 200, default="Electrical Engineering", null= True)
    hs_open_cut = models.IntegerField(default=0, null= True)
    hs_obc_cut = models.IntegerField(default=0, null= True)
    hs_sc_cut = models.IntegerField(default=0, null= True)
    hs_st_cut = models.IntegerField(default=0, null= True)
    hs_ews_cut = models.IntegerField(default=0, null= True)
    hs_open_f_cut = models.IntegerField(default=0, null= True)
    hs_obc_f_cut = models.IntegerField(default=0, null= True)
    hs_sc_f_cut = models.IntegerField(default=0, null= True)
    hs_st_f_cut = models.IntegerField(default=0, null= True)
    hs_ews_f_cut = models.IntegerField(default=0, null= True)
    open_cut = models.IntegerField(default=0, null= True)
    obc_cut = models.IntegerField(default=0, null= True)
    sc_cut = models.IntegerField(default=0, null= True)
    st_cut = models.IntegerField(default=0, null= True)
    ews_cut = models.IntegerField(default=0, null= True)
    open_f_cut = models.IntegerField(default=0, null= True)
    obc_f_cut = models.IntegerField(default=0, null= True)
    sc_f_cut = models.IntegerField(default=0, null= True)
    st_f_cut = models.IntegerField(default=0, null= True) 
    ews_f_cut = models.IntegerField(default=0, null= True)
    ad_open_cut = models.IntegerField(default=0, null= True)
    ad_obc_cut = models.IntegerField(default=0, null= True)
    ad_sc_cut = models.IntegerField(default=0, null= True)
    ad_st_cut = models.IntegerField(default=0, null= True)
    ad_ews_cut = models.IntegerField(default=0, null= True)
    ad_open_f_cut = models.IntegerField(default=0, null= True)
    ad_obc_f_cut = models.IntegerField(default=0, null= True)
    ad_sc_f_cut = models.IntegerField(default=0, null= True)
    ad_st_f_cut = models.IntegerField(default=0, null= True) 
    ad_ews_f_cut = models.IntegerField(default=0, null= True)

    def __str__(self):
        return self.name + '-' + self.college.college_name
class ECE(models.Model):#4
    college= models.ForeignKey(College, on_delete= models.CASCADE)
    name = models.CharField(max_length= 200, default="Electronics and Communication Engineering", null= True)
    hs_open_cut = models.IntegerField(default=0, null= True)
    hs_obc_cut = models.IntegerField(default=0, null= True)
    hs_sc_cut = models.IntegerField(default=0, null= True)
    hs_st_cut = models.IntegerField(default=0, null= True)
    hs_ews_cut = models.IntegerField(default=0, null= True)
    hs_open_f_cut = models.IntegerField(default=0, null= True)
    hs_obc_f_cut = models.IntegerField(default=0, null= True)
    hs_sc_f_cut = models.IntegerField(default=0, null= True)
    hs_st_f_cut = models.IntegerField(default=0, null= True)
    hs_ews_f_cut = models.IntegerField(default=0, null= True)
    open_cut = models.IntegerField(default=0, null= True)
    obc_cut = models.IntegerField(default=0, null= True)
    sc_cut = models.IntegerField(default=0, null= True)
    st_cut = models.IntegerField(default=0, null= True)
    ews_cut = models.IntegerField(default=0, null= True)
    open_f_cut = models.IntegerField(default=0, null= True)
    obc_f_cut = models.IntegerField(default=0, null= True)
    sc_f_cut = models.IntegerField(default=0, null= True)
    st_f_cut = models.IntegerField(default=0, null= True) 
    ews_f_cut = models.IntegerField(default=0, null= True)
    ad_open_cut = models.IntegerField(default=0, null= True)
    ad_obc_cut = models.IntegerField(default=0, null= True)
    ad_sc_cut = models.IntegerField(default=0, null= True)
    ad_st_cut = models.IntegerField(default=0, null= True)
    ad_ews_cut = models.IntegerField(default=0, null= True)
    ad_open_f_cut = models.IntegerField(default=0, null= True)
    ad_obc_f_cut = models.IntegerField(default=0, null= True)
    ad_sc_f_cut = models.IntegerField(default=0, null= True)
    ad_st_f_cut = models.IntegerField(default=0, null= True) 
    ad_ews_f_cut = models.IntegerField(default=0, null= True)

    def __str__(self):
        return self.name + '-' + self.college.college_name
class EEE(models.Model):#5
    college= models.ForeignKey(College, on_delete= models.CASCADE)
    name = models.CharField(max_length= 200, default="Electrical and Electronic Engineering", null= True)
    hs_open_cut = models.IntegerField(default=0, null= True)
    hs_obc_cut = models.IntegerField(default=0, null= True)
    hs_sc_cut = models.IntegerField(default=0, null= True)
    hs_st_cut = models.IntegerField(default=0, null= True)
    hs_ews_cut = models.IntegerField(default=0, null= True)
    hs_open_f_cut = models.IntegerField(default=0, null= True)
    hs_obc_f_cut = models.IntegerField(default=0, null= True)
    hs_sc_f_cut = models.IntegerField(default=0, null= True)
    hs_st_f_cut = models.IntegerField(default=0, null= True)
    hs_ews_f_cut = models.IntegerField(default=0, null= True)
    open_cut = models.IntegerField(default=0, null= True)
    obc_cut = models.IntegerField(default=0, null= True)
    sc_cut = models.IntegerField(default=0, null= True)
    st_cut = models.IntegerField(default=0, null= True)
    ews_cut = models.IntegerField(default=0, null= True)
    open_f_cut = models.IntegerField(default=0, null= True)
    obc_f_cut = models.IntegerField(default=0, null= True)
    sc_f_cut = models.IntegerField(default=0, null= True)
    st_f_cut = models.IntegerField(default=0, null= True) 
    ews_f_cut = models.IntegerField(default=0, null= True)
    ad_open_cut = models.IntegerField(default=0, null= True)
    ad_obc_cut = models.IntegerField(default=0, null= True)
    ad_sc_cut = models.IntegerField(default=0, null= True)
    ad_st_cut = models.IntegerField(default=0, null= True)
    ad_ews_cut = models.IntegerField(default=0, null= True)
    ad_open_f_cut = models.IntegerField(default=0, null= True)
    ad_obc_f_cut = models.IntegerField(default=0, null= True)
    ad_sc_f_cut = models.IntegerField(default=0, null= True)
    ad_st_f_cut = models.IntegerField(default=0, null= True) 
    ad_ews_f_cut = models.IntegerField(default=0, null= True)

    def __str__(self):
        return self.name + '-' + self.college.college_name
class mech(models.Model):#6
    college= models.ForeignKey(College, on_delete= models.CASCADE)
    name = models.CharField(max_length= 200, default="Mechanical Engineering", null= True)
    hs_open_cut = models.IntegerField(default=0, null= True)
    hs_obc_cut = models.IntegerField(default=0, null= True)
    hs_sc_cut = models.IntegerField(default=0, null= True)
    hs_st_cut = models.IntegerField(default=0, null= True)
    hs_ews_cut = models.IntegerField(default=0, null= True)
    hs_open_f_cut = models.IntegerField(default=0, null= True)
    hs_obc_f_cut = models.IntegerField(default=0, null= True)
    hs_sc_f_cut = models.IntegerField(default=0, null= True)
    hs_st_f_cut = models.IntegerField(default=0, null= True)
    hs_ews_f_cut = models.IntegerField(default=0, null= True)
    open_cut = models.IntegerField(default=0, null= True)
    obc_cut = models.IntegerField(default=0, null= True)
    sc_cut = models.IntegerField(default=0, null= True)
    st_cut = models.IntegerField(default=0, null= True)
    ews_cut = models.IntegerField(default=0, null= True)
    open_f_cut = models.IntegerField(default=0, null= True)
    obc_f_cut = models.IntegerField(default=0, null= True)
    sc_f_cut = models.IntegerField(default=0, null= True)
    st_f_cut = models.IntegerField(default=0, null= True) 
    ews_f_cut = models.IntegerField(default=0, null= True)
    ad_open_cut = models.IntegerField(default=0, null= True)
    ad_obc_cut = models.IntegerField(default=0, null= True)
    ad_sc_cut = models.IntegerField(default=0, null= True)
    ad_st_cut = models.IntegerField(default=0, null= True)
    ad_ews_cut = models.IntegerField(default=0, null= True)
    ad_open_f_cut = models.IntegerField(default=0, null= True)
    ad_obc_f_cut = models.IntegerField(default=0, null= True)
    ad_sc_f_cut = models.IntegerField(default=0, null= True)
    ad_st_f_cut = models.IntegerField(default=0, null= True) 
    ad_ews_f_cut = models.IntegerField(default=0, null= True)

    def __str__(self):
        return self.name + '-' + self.college.college_name
class chem(models.Model):#7
    college= models.ForeignKey(College, on_delete= models.CASCADE)
    name = models.CharField(max_length= 200, default="Chemical Engineering", null= True)
    hs_open_cut = models.IntegerField(default=0, null= True)
    hs_obc_cut = models.IntegerField(default=0, null= True)
    hs_sc_cut = models.IntegerField(default=0, null= True)
    hs_st_cut = models.IntegerField(default=0, null= True)
    hs_ews_cut = models.IntegerField(default=0, null= True)
    hs_open_f_cut = models.IntegerField(default=0, null= True)
    hs_obc_f_cut = models.IntegerField(default=0, null= True)
    hs_sc_f_cut = models.IntegerField(default=0, null= True)
    hs_st_f_cut = models.IntegerField(default=0, null= True)
    hs_ews_f_cut = models.IntegerField(default=0, null= True)
    open_cut = models.IntegerField(default=0, null= True)
    obc_cut = models.IntegerField(default=0, null= True)
    sc_cut = models.IntegerField(default=0, null= True)
    st_cut = models.IntegerField(default=0, null= True)
    ews_cut = models.IntegerField(default=0, null= True)
    open_f_cut = models.IntegerField(default=0, null= True)
    obc_f_cut = models.IntegerField(default=0, null= True)
    sc_f_cut = models.IntegerField(default=0, null= True)
    st_f_cut = models.IntegerField(default=0, null= True) 
    ews_f_cut = models.IntegerField(default=0, null= True)
    ad_open_cut = models.IntegerField(default=0, null= True)
    ad_obc_cut = models.IntegerField(default=0, null= True)
    ad_sc_cut = models.IntegerField(default=0, null= True)
    ad_st_cut = models.IntegerField(default=0, null= True)
    ad_ews_cut = models.IntegerField(default=0, null= True)
    ad_open_f_cut = models.IntegerField(default=0, null= True)
    ad_obc_f_cut = models.IntegerField(default=0, null= True)
    ad_sc_f_cut = models.IntegerField(default=0, null= True)
    ad_st_f_cut = models.IntegerField(default=0, null= True) 
    ad_ews_f_cut = models.IntegerField(default=0, null= True)

    def __str__(self):
        return self.name + '-' + self.college.college_name
class civil(models.Model):#8
    college= models.ForeignKey(College, on_delete= models.CASCADE)
    name = models.CharField(max_length= 200, default="Civil Engineering", null= True)
    hs_open_cut = models.IntegerField(default=0, null= True)
    hs_obc_cut = models.IntegerField(default=0, null= True)
    hs_sc_cut = models.IntegerField(default=0, null= True)
    hs_st_cut = models.IntegerField(default=0, null= True)
    hs_ews_cut = models.IntegerField(default=0, null= True)
    hs_open_f_cut = models.IntegerField(default=0, null= True)
    hs_obc_f_cut = models.IntegerField(default=0, null= True)
    hs_sc_f_cut = models.IntegerField(default=0, null= True)
    hs_st_f_cut = models.IntegerField(default=0, null= True)
    hs_ews_f_cut = models.IntegerField(default=0, null= True)
    open_cut = models.IntegerField(default=0, null= True)
    obc_cut = models.IntegerField(default=0, null= True)
    sc_cut = models.IntegerField(default=0, null= True)
    st_cut = models.IntegerField(default=0, null= True)
    ews_cut = models.IntegerField(default=0, null= True)
    open_f_cut = models.IntegerField(default=0, null= True)
    obc_f_cut = models.IntegerField(default=0, null= True)
    sc_f_cut = models.IntegerField(default=0, null= True)
    st_f_cut = models.IntegerField(default=0, null= True) 
    ews_f_cut = models.IntegerField(default=0, null= True)
    ad_open_cut = models.IntegerField(default=0, null= True)
    ad_obc_cut = models.IntegerField(default=0, null= True)
    ad_sc_cut = models.IntegerField(default=0, null= True)
    ad_st_cut = models.IntegerField(default=0, null= True)
    ad_ews_cut = models.IntegerField(default=0, null= True)
    ad_open_f_cut = models.IntegerField(default=0, null= True)
    ad_obc_f_cut = models.IntegerField(default=0, null= True)
    ad_sc_f_cut = models.IntegerField(default=0, null= True)
    ad_st_f_cut = models.IntegerField(default=0, null= True) 
    ad_ews_f_cut = models.IntegerField(default=0, null= True)

    def __str__(self):
        return self.name + '-' + self.college.college_name
class meta(models.Model):#9
    college= models.ForeignKey(College, on_delete= models.CASCADE)
    name = models.CharField(max_length= 200, default="Metallurgical Engineering", null= True)
    hs_open_cut = models.IntegerField(default=0, null= True)
    hs_obc_cut = models.IntegerField(default=0, null= True)
    hs_sc_cut = models.IntegerField(default=0, null= True)
    hs_st_cut = models.IntegerField(default=0, null= True)
    hs_ews_cut = models.IntegerField(default=0, null= True)
    hs_open_f_cut = models.IntegerField(default=0, null= True)
    hs_obc_f_cut = models.IntegerField(default=0, null= True)
    hs_sc_f_cut = models.IntegerField(default=0, null= True)
    hs_st_f_cut = models.IntegerField(default=0, null= True)
    hs_ews_f_cut = models.IntegerField(default=0, null= True)
    open_cut = models.IntegerField(default=0, null= True)
    obc_cut = models.IntegerField(default=0, null= True)
    sc_cut = models.IntegerField(default=0, null= True)
    st_cut = models.IntegerField(default=0, null= True)
    ews_cut = models.IntegerField(default=0, null= True)
    open_f_cut = models.IntegerField(default=0, null= True)
    obc_f_cut = models.IntegerField(default=0, null= True)
    sc_f_cut = models.IntegerField(default=0, null= True)
    st_f_cut = models.IntegerField(default=0, null= True) 
    ews_f_cut = models.IntegerField(default=0, null= True)
    ad_open_cut = models.IntegerField(default=0, null= True)
    ad_obc_cut = models.IntegerField(default=0, null= True)
    ad_sc_cut = models.IntegerField(default=0, null= True)
    ad_st_cut = models.IntegerField(default=0, null= True)
    ad_ews_cut = models.IntegerField(default=0, null= True)
    ad_open_f_cut = models.IntegerField(default=0, null= True)
    ad_obc_f_cut = models.IntegerField(default=0, null= True)
    ad_sc_f_cut = models.IntegerField(default=0, null= True)
    ad_st_f_cut = models.IntegerField(default=0, null= True) 
    ad_ews_f_cut = models.IntegerField(default=0, null= True)

    def __str__(self):
        return self.name + '-' + self.college.college_name
class mining(models.Model):#10
    college= models.ForeignKey(College, on_delete= models.CASCADE)
    name = models.CharField(max_length= 200, default="Mining Engineering", null= True)
    hs_open_cut = models.IntegerField(default=0, null= True)
    hs_obc_cut = models.IntegerField(default=0, null= True)
    hs_sc_cut = models.IntegerField(default=0, null= True)
    hs_st_cut = models.IntegerField(default=0, null= True)
    hs_ews_cut = models.IntegerField(default=0, null= True)
    hs_open_f_cut = models.IntegerField(default=0, null= True)
    hs_obc_f_cut = models.IntegerField(default=0, null= True)
    hs_sc_f_cut = models.IntegerField(default=0, null= True)
    hs_st_f_cut = models.IntegerField(default=0, null= True)
    hs_ews_f_cut = models.IntegerField(default=0, null= True)
    open_cut = models.IntegerField(default=0, null= True)
    obc_cut = models.IntegerField(default=0, null= True)
    sc_cut = models.IntegerField(default=0, null= True)
    st_cut = models.IntegerField(default=0, null= True)
    ews_cut = models.IntegerField(default=0, null= True)
    open_f_cut = models.IntegerField(default=0, null= True)
    obc_f_cut = models.IntegerField(default=0, null= True)
    sc_f_cut = models.IntegerField(default=0, null= True)
    st_f_cut = models.IntegerField(default=0, null= True) 
    ews_f_cut = models.IntegerField(default=0, null= True)
    ad_open_cut = models.IntegerField(default=0, null= True)
    ad_obc_cut = models.IntegerField(default=0, null= True)
    ad_sc_cut = models.IntegerField(default=0, null= True)
    ad_st_cut = models.IntegerField(default=0, null= True)
    ad_ews_cut = models.IntegerField(default=0, null= True)
    ad_open_f_cut = models.IntegerField(default=0, null= True)
    ad_obc_f_cut = models.IntegerField(default=0, null= True)
    ad_sc_f_cut = models.IntegerField(default=0, null= True)
    ad_st_f_cut = models.IntegerField(default=0, null= True) 
    ad_ews_f_cut = models.IntegerField(default=0, null= True)

    def __str__(self):
        return self.name + '-' + self.college.college_name
class BioEn(models.Model):#11
    college= models.ForeignKey(College, on_delete= models.CASCADE)
    name = models.CharField(max_length= 200, default="Bio Engineering", null= True)
    hs_open_cut = models.IntegerField(default=0, null= True)
    hs_obc_cut = models.IntegerField(default=0, null= True)
    hs_sc_cut = models.IntegerField(default=0, null= True)
    hs_st_cut = models.IntegerField(default=0, null= True)
    hs_ews_cut = models.IntegerField(default=0, null= True)
    hs_open_f_cut = models.IntegerField(default=0, null= True)
    hs_obc_f_cut = models.IntegerField(default=0, null= True)
    hs_sc_f_cut = models.IntegerField(default=0, null= True)
    hs_st_f_cut = models.IntegerField(default=0, null= True)
    hs_ews_f_cut = models.IntegerField(default=0, null= True)
    open_cut = models.IntegerField(default=0, null= True)
    obc_cut = models.IntegerField(default=0, null= True)
    sc_cut = models.IntegerField(default=0, null= True)
    st_cut = models.IntegerField(default=0, null= True)
    ews_cut = models.IntegerField(default=0, null= True)
    open_f_cut = models.IntegerField(default=0, null= True)
    obc_f_cut = models.IntegerField(default=0, null= True)
    sc_f_cut = models.IntegerField(default=0, null= True)
    st_f_cut = models.IntegerField(default=0, null= True) 
    ews_f_cut = models.IntegerField(default=0, null= True)
    ad_open_cut = models.IntegerField(default=0, null= True)
    ad_obc_cut = models.IntegerField(default=0, null= True)
    ad_sc_cut = models.IntegerField(default=0, null= True)
    ad_st_cut = models.IntegerField(default=0, null= True)
    ad_ews_cut = models.IntegerField(default=0, null= True)
    ad_open_f_cut = models.IntegerField(default=0, null= True)
    ad_obc_f_cut = models.IntegerField(default=0, null= True)
    ad_sc_f_cut = models.IntegerField(default=0, null= True)
    ad_st_f_cut = models.IntegerField(default=0, null= True) 
    ad_ews_f_cut = models.IntegerField(default=0, null= True)

    def __str__(self):
        return self.name + '-' + self.college.college_name

class other(models.Model):#12
    college= models.ForeignKey(College, on_delete= models.CASCADE)
    name = models.CharField(max_length= 200, default="other", null= True)
    hs_open_cut = models.IntegerField(default=0, null= True)
    hs_obc_cut = models.IntegerField(default=0, null= True)
    hs_sc_cut = models.IntegerField(default=0, null= True)
    hs_st_cut = models.IntegerField(default=0, null= True)
    hs_ews_cut = models.IntegerField(default=0, null= True)
    hs_open_f_cut = models.IntegerField(default=0, null= True)
    hs_obc_f_cut = models.IntegerField(default=0, null= True)
    hs_sc_f_cut = models.IntegerField(default=0, null= True)
    hs_st_f_cut = models.IntegerField(default=0, null= True)
    hs_ews_f_cut = models.IntegerField(default=0, null= True)
    open_cut = models.IntegerField(default=0, null= True)
    obc_cut = models.IntegerField(default=0, null= True)
    sc_cut = models.IntegerField(default=0, null= True)
    st_cut = models.IntegerField(default=0, null= True)
    ews_cut = models.IntegerField(default=0, null= True)
    open_f_cut = models.IntegerField(default=0, null= True)
    obc_f_cut = models.IntegerField(default=0, null= True)
    sc_f_cut = models.IntegerField(default=0, null= True)
    st_f_cut = models.IntegerField(default=0, null= True) 
    ews_f_cut = models.IntegerField(default=0, null= True)
    ad_open_cut = models.IntegerField(default=0, null= True)
    ad_obc_cut = models.IntegerField(default=0, null= True)
    ad_sc_cut = models.IntegerField(default=0, null= True)
    ad_st_cut = models.IntegerField(default=0, null= True)
    ad_ews_cut = models.IntegerField(default=0, null= True)
    ad_open_f_cut = models.IntegerField(default=0, null= True)
    ad_obc_f_cut = models.IntegerField(default=0, null= True)
    ad_sc_f_cut = models.IntegerField(default=0, null= True)
    ad_st_f_cut = models.IntegerField(default=0, null= True) 
    ad_ews_f_cut = models.IntegerField(default=0, null= True)

    def __str__(self):
        return self.name + '-' + self.college.college_name
